/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_towson_android_ndk_helloworld_java_jni_interface */

#ifndef _Included_com_example_towson_android_ndk_helloworld_java_jni_interface
#define _Included_com_example_towson_android_ndk_helloworld_java_jni_interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_towson_android_ndk_helloworld_java_jni_interface
 * Method:    get_jni_string
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_towson_android_1ndk_1helloworld_java_1jni_1interface_get_1jni_1string
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
